In [1]:
import pandas as pd

In [2]:
tabela5 = pd.read_excel('CD2022_Populacao_2010_Compatibilizada_20231222.xlsx', header=2)
tabela5 = tabela5.drop(columns=['Unnamed: 0'])
tabela5.columns = ['UF','COD_UF','COD_MUNIC','NOME_MUNIC','POP_2010_sinopse','POP_2010_compat','POP_2022']
ufs = ['RO','AC','AM','RR','PA','AP','TO','MA','PI','CE','RN','PB','PE','AL','SE','BA','MG','ES','RJ','SP','PR','SC','RS','MS','MT','GO','DF']
tabela5 = tabela5[tabela5['UF'].isin(ufs)].copy()
tabela5['POP_2010_compat'] = pd.to_numeric(tabela5['POP_2010_compat'], errors='coerce')
tabela5['POP_2022'] = pd.to_numeric(tabela5['POP_2022'], errors='coerce')
tabela5.head()

,UF,COD_UF,COD_MUNIC,NOME_MUNIC,POP_2010_sinopse,POP_2010_compat,POP_2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [3]:
populacao_por_estado = (
    tabela5.groupby('UF')[['POP_2010_compat','POP_2022']]
    .sum()
    .reset_index()
)
populacao_por_estado['CRESCIMENTO_2010_2022'] = populacao_por_estado['POP_2022'] - populacao_por_estado['POP_2010_compat']
populacao_por_estado = populacao_por_estado.sort_values('CRESCIMENTO_2010_2022', ascending=False)
populacao_por_estado

    UF  POP_2010_compat    POP_2022  CRESCIMENTO_2010_2022
25  SP       41262199.0  44411238.0              3149039.0
23  SC        6248436.0   7610361.0              1361925.0
8   GO        6001789.0   7056495.0              1054706.0
17  PR       10444526.0  11444380.0               999854.0
10  MG       19597330.0  20539989.0               942659.0
12  MT        3035122.0   3658649.0               623527.0
13  PA        7581051.0   8120131.0               539080.0
2   AM        3483985.0   3941613.0               457628.0
5   CE        8451644.0   8794957.0               343313.0
7   ES        3514952.0   3833712.0               318760.0
11  MS        2449024.0   2757013.0               307989.0
15  PE        8796055.0   9058931.0               262876.0
6   DF        2572159.0   2817381.0               245222.0
14  PB        3766528.0   3974687.0               208159.0
9   MA        6574789.0   6776699.0               201910.0
22  RS       10693929.0  10882965.0               189036.0
21  RR         450479.0    636707.0               186228.0
16  PI        3119097.0   3271199.0               152102.0
24  SE        2067852.0   2210004.0               142152.0
19  RN        3168027.0   3302729.0               134702.0
26  TO        1383445.0   1511460.0               128015.0
4   BA       14017071.0  14141626.0               124555.0
0   AC         733559.0    830018.0                96459.0
18  RJ       15989929.0  16055174.0                65245.0
3   AP         669526.0    733759.0                64233.0
20  RO        1562409.0   1581196.0                18787.0
1   AL        3120887.0   3127683.0                 6796.0

In [4]:
populacao_por_estado.to_csv('populacao_por_estado.csv', index=False, encoding='utf-8-sig')
print('Arquivo populacao_por_estado.csv salvo com sucesso!')

Arquivo populacao_por_estado.csv salvo com sucesso!

In [5]:
populacao_por_municipio = (
    tabela5.groupby(['UF','COD_UF','COD_MUNIC','NOME_MUNIC'])[['POP_2010_compat','POP_2022']]
    .sum()
    .reset_index()
)
populacao_por_municipio['CRESCIMENTO_2010_2022'] = populacao_por_municipio['POP_2022'] - populacao_por_municipio['POP_2010_compat']
populacao_por_municipio = populacao_por_municipio.sort_values('CRESCIMENTO_2010_2022', ascending=False)
populacao_por_municipio

,UF,COD_UF,COD_MUNIC,NOME_MUNIC,POP_2010_compat,POP_2022,CRESCIMENTO_2010_2022
161,AM,13.0,2603.0,Manaus,1802014.0,2063689.0,261675.0
803,DF,53.0,108.0,Brasília,2572159.0,2817381.0,245222.0
5348,SP,35.0,50308.0,São Paulo,11253503.0,11451999.0,198496.0
5367,SP,35.0,52205.0,Sorocaba,586816.0,723682.0,136866.0
976,GO,52.0,8707.0,Goiânia,1301912.0,1437366.0,135454.0
...,...,...,...,...,...,...,...
4244,RS,43.0,14902.0,Porto Alegre,1409351.0,1332845.0,-76506.0
2436,PA,15.0,1402.0,Belém,1393399.0,1303403.0,-89996.0
3665,RJ,33.0,4904.0,São Gonçalo,999728.0,896744.0,-102984.0
3660,RJ,33.0,4557.0,Rio de Janeiro,6320446.0,6211223.0,-109223.0
537,BA,29.0,27408.0,Salvador,2675656.0,2417678.0,-257978.0

In [6]:
populacao_por_municipio.to_csv('populacao_por_municipio.csv', index=False, encoding='utf-8-sig')
print('Arquivo populacao_por_municipio.csv salvo com sucesso!')

Arquivo populacao_por_municipio.csv salvo com sucesso!